version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "123456aA@"
        MSSQL_PID: Evaluation
    ports:
        - "1433:1433"
   
  app-api:
    build:
        dockerfile: Dockerfile
    ports:
        - "8080:80" 
    depends_on:
        - ms-sql-server  